spring:
  config:
    use-legacy-processing: true
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/projet_stagiaire?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  application:
    name: Easyschool
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: easyschool-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: service-test-scheduling-
      pool:
        size: 2
  output:
    ansi:
      console-available: true


server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

application:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,message'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: ODk2YWY3ODg0MDA0YTgzMWNiNGZlNDBlNWJhMjYzNmJhZDEwMDM0OWNhNTU0Y2QwNjA5OGM1ODMzZmJjZWY2N2FmY2ZhOTViYjkwYTI1OWMxNGRmZmYyNmQ4ODNlNzMxMDQyNTJjMTFkOTRmM2Q1YzNiZDkyZjM2N2E4MmNlZDg=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  clientApp:
    name: 'EasySchool'
  swagger:
    default-include-pattern: /api/.*
    title: EasySchool API
    description: EasySchool API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license: unlicensed
    license-url:
  upload:
    resources-server-store: C:/Users/report/
    resources-server-store-url: http://localhost:8080/uploads/

info:
  project:
    version: 0.0.1

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump']
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      prometheus:
        enabled: false
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
